# Generated by Django 3.1.6 on 2021-05-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_empleado_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres completos'),
        ),
    ]
