# Generated by Django 3.1.6 on 2021-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('shor_name', models.CharField(max_length=50, verbose_name='nombreCorto')),
                ('anulate', models.BooleanField(default=False, verbose_name='anulado')),
            ],
            options={
                'verbose_name': 'Mi Departamento',
                'verbose_name_plural': 'Areas de la Empresa',
                'ordering': ['-name'],
                'unique_together': {('name', 'shor_name')},
            },
        ),
    ]
